server:
  port: 8010
file_address: laststand/files/
virtualUploadPath: /getFiles


spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  security:
      user:
        name: user
        password: 1234
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${file_address}

  rabbitmq:
    host: 43.143.250.239
    port: 5672
    username: chenhong
    password: 12345
    publisher-confirms: true  # 开启Rabbitmq发送消息确认机制，发送消息到队列并触发回调方法
    # 确认消息已发送到队列
    publisher-returns: true
    listener:
      simple:
        concurrency: 10 #消费者数量
        max-concurrency: 10 #最大消费者数量
        prefetch: 1 #限流（消费者每次从队列获取的消息数量）
        auto-startup: true  #启动时自动启动容器
        acknowledge-mode: manual #开启ACK手动确认模式

  mail:
    defaultEncoding: UTF-8
    host: smtp.qq.com
    username: 1875435468@qq.com
    password: ccmufaurlatlhhja
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  datasource:
    url: jdbc:mysql://43.143.250.239:3306/bikebackend?userSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: bikebackend
    password: laststand
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari: # 使用springboot默认的连接池hikari
      minimum-idle: 10 # 池中维护的最小空闲连接数，默认为 10 个
      maximum-pool-size: 100 # 池中最大连接数，包括闲置和使用中的连接

  data:
    redis:
      host: 43.143.250.239
      port: 1764
      password: myredis_ch1234567
      database: 0
      timeout: 6000ms
  redis:
    lettuce:
        pool:
          max-idle: 16
          max-active: 32
          min-idle: 8

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xiaominfo.knife4j.demo.web
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

